"""Frozen semantic vocabularies for the M05 identity contract."""

from __future__ import annotations

from enum import Enum

__all__ = [
    "TraitCriticality", "TraitMutability", "TraitApplicability", "TraitPolarity",
    "DNAIdentityLevel", "DNAFamily", "AnchorAuthorityClass", "AnchorLifecycleOperation",
    "LinkRequirement", "LinkFreshness", "ObligationExpectation", "DriftDimension",
    "DriftState", "MutationDecisionKind", "LineageRelation", "CompatibilityOutcome",
    "CompatibilityAxisState", "MigrationActionKind", "IdentityContinuity",
    "PortabilityLevel", "DependencyKind", "ImportAdmissionState", "PackageLifecycle",
    "RiskCode", "RiskSeverity", "ReadinessState",
    "DriftEvidenceResult",
    "ImportCollisionOutcome",
]


class TraitCriticality(str, Enum):
    IDENTITY_DEFINING = "IDENTITY_DEFINING"
    IDENTITY_SIGNIFICANT = "IDENTITY_SIGNIFICANT"
    CONSISTENCY_RELEVANT = "CONSISTENCY_RELEVANT"
    CONTEXTUAL = "CONTEXTUAL"
    DERIVED_EVIDENCE_ONLY = "DERIVED_EVIDENCE_ONLY"


class TraitMutability(str, Enum):
    IMMUTABLE = "IMMUTABLE"
    MUTABLE_WITH_EXPLICIT_POLICY = "MUTABLE_WITH_EXPLICIT_POLICY"
    MUTABLE_WITHIN_BOUNDS = "MUTABLE_WITHIN_BOUNDS"
    CONTEXTUAL_VARIANT = "CONTEXTUAL_VARIANT"
    DERIVED_ONLY = "DERIVED_ONLY"


class TraitApplicability(str, Enum):
    PRESENT = "PRESENT"
    UNKNOWN = "UNKNOWN"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    INTENTIONALLY_UNCONSTRAINED = "INTENTIONALLY_UNCONSTRAINED"


class TraitPolarity(str, Enum):
    REQUIRED = "REQUIRED"
    PROHIBITED = "PROHIBITED"


class DNAIdentityLevel(str, Enum):
    CLASS = "CLASS"
    ARCHETYPE = "ARCHETYPE"
    INDIVIDUAL = "INDIVIDUAL"
    VARIANT = "VARIANT"
    PRODUCT_FAMILY = "PRODUCT_FAMILY"
    MODEL = "MODEL"
    VARIANT_SKU = "VARIANT_SKU"
    PACKAGE_VARIANT = "PACKAGE_VARIANT"
    PHYSICAL_INSTANCE = "PHYSICAL_INSTANCE"


class DNAFamily(str, Enum):
    GENERIC = "GENERIC"
    CHARACTER = "CHARACTER"
    CREATURE = "CREATURE"
    OBJECT = "OBJECT"
    PRODUCT = "PRODUCT"
    ENVIRONMENT = "ENVIRONMENT"
    SCENE = "SCENE"
    EXTENSION = "EXTENSION"


class AnchorAuthorityClass(str, Enum):
    CANONICAL = "CANONICAL"
    BOUND_EXTERNAL = "BOUND_EXTERNAL"
    REPRESENTATION = "REPRESENTATION"
    PROVENANCE = "PROVENANCE"
    OBSERVATION = "OBSERVATION"
    PROPOSED = "PROPOSED"
    REVOKED = "REVOKED"


class AnchorLifecycleOperation(str, Enum):
    ADD = "ADD"
    REBIND = "REBIND"
    SUPERSEDE = "SUPERSEDE"
    REVOKE = "REVOKE"
    RESTORE = "RESTORE"
    EXPIRE = "EXPIRE"
    INVALIDATE_EVIDENCE = "INVALIDATE_EVIDENCE"


class LinkRequirement(str, Enum):
    REQUIRED = "REQUIRED"
    OPTIONAL = "OPTIONAL"


class LinkFreshness(str, Enum):
    CURRENT = "CURRENT"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class ObligationExpectation(str, Enum):
    EXACT = "EXACT"
    BOUNDED = "BOUNDED"
    ROLE_COMPATIBLE = "ROLE_COMPATIBLE"
    CONTEXTUAL = "CONTEXTUAL"
    OPAQUE_REFERENCE_ONLY = "OPAQUE_REFERENCE_ONLY"


class DriftDimension(str, Enum):
    NUMERIC = "NUMERIC"
    CATEGORICAL = "CATEGORICAL"
    STRUCTURAL = "STRUCTURAL"
    COMPONENT = "COMPONENT"
    RELATION = "RELATION"
    ANCHOR = "ANCHOR"
    LINK = "LINK"
    CROSS_MODAL = "CROSS_MODAL"
    MISSING_REQUIRED = "MISSING_REQUIRED"
    FAMILY_PROFILE = "FAMILY_PROFILE"
    COLLISION_SPLIT = "COLLISION_SPLIT"


class DriftEvidenceResult(str, Enum):
    MATCH = "MATCH"
    DIFFERENT = "DIFFERENT"
    ALLOWED_VARIATION = "ALLOWED_VARIATION"
    MISSING = "MISSING"
    UNKNOWN = "UNKNOWN"


class DriftState(str, Enum):
    NO_DRIFT = "NO_DRIFT"
    WITHIN_DECLARED_VARIATION = "WITHIN_DECLARED_VARIATION"
    OBSERVATION_UNCERTAIN = "OBSERVATION_UNCERTAIN"
    REPRESENTATION_DRIFT = "REPRESENTATION_DRIFT"
    IDENTITY_RELEVANT_DRIFT = "IDENTITY_RELEVANT_DRIFT"
    MUTATION_CANDIDATE = "MUTATION_CANDIDATE"
    IDENTITY_BREAK_CANDIDATE = "IDENTITY_BREAK_CANDIDATE"
    COLLISION_OR_SPLIT_CANDIDATE = "COLLISION_OR_SPLIT_CANDIDATE"
    INDETERMINATE = "INDETERMINATE"


class MutationDecisionKind(str, Enum):
    REJECT = "REJECT"
    REPAIR_INSTEAD = "REPAIR_INSTEAD"
    CONTEXTUAL_VARIATION_ONLY = "CONTEXTUAL_VARIATION_ONLY"
    ADMIT_SAME_IDENTITY_REVISION = "ADMIT_SAME_IDENTITY_REVISION"
    REQUIRE_NEW_IDENTITY = "REQUIRE_NEW_IDENTITY"
    REQUIRE_SPLIT = "REQUIRE_SPLIT"
    REQUEST_MORE_EVIDENCE = "REQUEST_MORE_EVIDENCE"


class LineageRelation(str, Enum):
    SAME_IDENTITY_REVISION = "SAME_IDENTITY_REVISION"
    VARIANT_DERIVATION = "VARIANT_DERIVATION"
    ARCHETYPE_DERIVATION = "ARCHETYPE_DERIVATION"
    IDENTITY_BREAK_DERIVATION = "IDENTITY_BREAK_DERIVATION"
    SPLIT_CHILD = "SPLIT_CHILD"
    CONSOLIDATION_CONTINUATION = "CONSOLIDATION_CONTINUATION"
    TEMPLATE_INSTANTIATION = "TEMPLATE_INSTANTIATION"


class CompatibilityOutcome(str, Enum):
    EXACT = "EXACT"
    COMPATIBLE = "COMPATIBLE"
    COMPATIBLE_WITH_LOSS = "COMPATIBLE_WITH_LOSS"
    REQUIRES_MIGRATION = "REQUIRES_MIGRATION"
    BREAKING = "BREAKING"
    INDETERMINATE = "INDETERMINATE"


class CompatibilityAxisState(str, Enum):
    EXACT = "EXACT"
    COMPATIBLE = "COMPATIBLE"
    LOSS = "LOSS"
    MIGRATION_REQUIRED = "MIGRATION_REQUIRED"
    BREAKING = "BREAKING"
    UNKNOWN = "UNKNOWN"


class MigrationActionKind(str, Enum):
    PRESERVE = "PRESERVE"
    RENAME = "RENAME"
    DROP = "DROP"
    DEFAULT = "DEFAULT"


class IdentityContinuity(str, Enum):
    PRESERVE = "PRESERVE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BREAK_REQUIRED = "BREAK_REQUIRED"


class PortabilityLevel(str, Enum):
    INTERFACE_ONLY = "INTERFACE_ONLY"
    PORTABLE_CANONICAL = "PORTABLE_CANONICAL"
    PRODUCTION_REFERENCE = "PRODUCTION_REFERENCE"
    RESTRICTED_REFERENCE = "RESTRICTED_REFERENCE"


class DependencyKind(str, Enum):
    REQUIRED_CANONICAL = "REQUIRED_CANONICAL"
    REQUIRED_EXTERNAL_DNA = "REQUIRED_EXTERNAL_DNA"
    OPTIONAL_EXTERNAL_DNA = "OPTIONAL_EXTERNAL_DNA"
    POLICY_REF = "POLICY_REF"
    SCHEMA_REF = "SCHEMA_REF"
    EVIDENCE_REF = "EVIDENCE_REF"
    TOOLING_CAPABILITY = "TOOLING_CAPABILITY"


class ImportAdmissionState(str, Enum):
    PARSED = "PARSED"
    VALIDATED = "VALIDATED"
    COMPATIBILITY_CHECKED = "COMPATIBILITY_CHECKED"
    POLICY_CHECKED = "POLICY_CHECKED"
    QUARANTINED = "QUARANTINED"
    ADMISSION_PROPOSED = "ADMISSION_PROPOSED"
    ADMITTED = "ADMITTED"
    REJECTED = "REJECTED"


class ImportCollisionOutcome(str, Enum):
    EXACT_DUPLICATE_NOOP = "EXACT_DUPLICATE_NOOP"
    SAME_IDENTITY_CONTINUATION = "SAME_IDENTITY_CONTINUATION"
    GOVERNED_EQUIVALENCE = "GOVERNED_EQUIVALENCE"
    KEEP_DISTINCT = "KEEP_DISTINCT"


class PackageLifecycle(str, Enum):
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    SECURITY_RESTRICTED = "SECURITY_RESTRICTED"
    RETIRED = "RETIRED"


class RiskCode(str, Enum):
    CLASS_INDIVIDUAL_COLLAPSE = "CLASS_INDIVIDUAL_COLLAPSE"
    COMPONENT_CHURN = "COMPONENT_CHURN"
    CONTEXTUAL_STATE_LEAKAGE = "CONTEXTUAL_STATE_LEAKAGE"
    STALE_OR_MISSING_LINK = "STALE_OR_MISSING_LINK"
    CAMPAIGN_BRAND_CONFUSION = "CAMPAIGN_BRAND_CONFUSION"
    UNAUTHORIZED_MUTATION = "UNAUTHORIZED_MUTATION"
    SIMILARITY_AUTO_MERGE = "SIMILARITY_AUTO_MERGE"
    HISTORY_ERASURE = "HISTORY_ERASURE"
    PACKAGE_OVERWRITE = "PACKAGE_OVERWRITE"
    HIDDEN_LOSSY_MIGRATION = "HIDDEN_LOSSY_MIGRATION"
    STRIPPED_RIGHTS_SECURITY_REF = "STRIPPED_RIGHTS_SECURITY_REF"
    EXECUTABLE_PAYLOAD_ATTEMPT = "EXECUTABLE_PAYLOAD_ATTEMPT"


class RiskSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ReadinessState(str, Enum):
    READY = "READY"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    BLOCKED = "BLOCKED"
    INDETERMINATE = "INDETERMINATE"
