"""Frozen 150-invariant inventory and exact family mapping from the admitted contract."""

from __future__ import annotations

from dataclasses import dataclass

from .errors import DNAIntegrityError

__all__ = ["DNAInvariant", "M05_INVARIANTS", "invariants_for_family", "validate_invariant_catalog"]


@dataclass(frozen=True)
class DNAInvariant:
    number: int
    family: str
    statement: str
    proof_method: str


M05_INVARIANTS = (
    DNAInvariant(1, "F-M05-01", "`dna_id` is stable and opaque; display metadata never defines it.", "test_family_01_behavior"),
    DNAInvariant(2, "F-M05-01", "file/path/URL/storage location never defines persistent identity.", "test_family_01_behavior"),
    DNAInvariant(3, "F-M05-01", "content digest identifies representation/content, not automatically subject identity.", "test_family_01_behavior"),
    DNAInvariant(4, "F-M05-02", "provider/model/workflow IDs never define canonical M05 identity.", "test_family_02_behavior"),
    DNAInvariant(5, "F-M05-02", "prompts and generated output IDs never define canonical identity.", "test_family_02_behavior"),
    DNAInvariant(6, "F-M05-02", "embeddings/perceptual hashes/similarity scores are evidence only.", "test_family_02_behavior"),
    DNAInvariant(7, "F-M05-03", "DNA revisions are immutable.", "test_family_03_behavior"),
    DNAInvariant(8, "F-M05-04", "M02 remains branch/project/history authority.", "test_family_04_behavior"),
    DNAInvariant(9, "F-M05-04", "M06 operational production-state/content-addressed persistence/reconstruction and M55 media CAS/storage/cache/archive remain external authorities; M05 owns neither.", "test_family_04_behavior"),
    DNAInvariant(10, "F-M05-03", "M04 remains provider-neutral representation authority.", "test_family_03_behavior"),
    DNAInvariant(11, "F-M05-02", "canonical traits declare schema family/version.", "test_family_02_behavior"),
    DNAInvariant(12, "F-M05-02", "canonical traits declare identity criticality.", "test_family_02_behavior"),
    DNAInvariant(13, "F-M05-02", "canonical traits declare mutability class.", "test_family_02_behavior"),
    DNAInvariant(14, "F-M05-02", "PRESENT/UNKNOWN/NOT_APPLICABLE/INTENTIONALLY_UNCONSTRAINED are distinct states.", "test_family_02_behavior"),
    DNAInvariant(15, "F-M05-06", "identity-defining immutable traits cannot change without identity break or explicit governed rule.", "test_family_06_behavior"),
    DNAInvariant(16, "F-M05-06", "downstream scarcity/provider limitation cannot weaken a trait's criticality/mutability.", "test_family_06_behavior"),
    DNAInvariant(17, "F-M05-01", "observed/generated/provider data cannot self-promote into canonical DNA.", "test_family_01_behavior"),
    DNAInvariant(18, "F-M05-01", "every canonical fact has provenance/policy reachability.", "test_family_01_behavior"),
    DNAInvariant(19, "F-M05-04", "unknown mandatory trait schema fails closed.", "test_family_04_behavior"),
    DNAInvariant(20, "F-M05-04", "opaque optional traits require explicit preservation policy.", "test_family_04_behavior"),
    DNAInvariant(21, "F-M05-05", "representation anchors require explicit DNA binding.", "test_family_05_behavior"),
    DNAInvariant(22, "F-M05-03", "M04 identity and M05 identity are not implicitly equivalent.", "test_family_03_behavior"),
    DNAInvariant(23, "F-M05-03", "aliases never merge identities implicitly.", "test_family_03_behavior"),
    DNAInvariant(24, "F-M05-19", "equivalence is a governed claim, not a similarity threshold.", "test_family_19_behavior"),
    DNAInvariant(25, "F-M05-19", "canonical fingerprint excludes evidence/cache/location noise.", "test_family_19_behavior"),
    DNAInvariant(26, "F-M05-05", "fingerprint change does not itself authorize mutation.", "test_family_05_behavior"),
    DNAInvariant(27, "F-M05-05", "DNA projection declares consumed required/optional traits.", "test_family_05_behavior"),
    DNAInvariant(28, "F-M05-05", "unsupported mandatory projected identity traits cannot disappear silently.", "test_family_05_behavior"),
    DNAInvariant(29, "F-M05-22", "rights/privacy/provenance evidence is referenced with minimization; M05 does not seize M53/M54 authority.", "test_family_22_behavior"),
    DNAInvariant(30, "F-M05-07", "HIVE/agents may retrieve/propose identity context but cannot mutate canonical DNA directly.", "test_family_07_behavior"),
    DNAInvariant(31, "F-M05-07", "family specialization must reuse the S01 identity core rather than create an independent identity engine.", "test_family_07_behavior"),
    DNAInvariant(32, "F-M05-07", "CLASS, ARCHETYPE, INDIVIDUAL and VARIANT remain semantically distinct.", "test_family_07_behavior"),
    DNAInvariant(33, "F-M05-07", "visual similarity cannot infer semantic identity level.", "test_family_07_behavior"),
    DNAInvariant(34, "F-M05-08", "family-profile defaults cannot silently override explicit trait criticality/mutability.", "test_family_08_behavior"),
    DNAInvariant(35, "F-M05-08", "trait bundles cannot become independent subject identities.", "test_family_08_behavior"),
    DNAInvariant(36, "F-M05-09", "component index/order/name never defines component identity.", "test_family_09_behavior"),
    DNAInvariant(37, "F-M05-09", "M04 node identity cannot silently define M05 component identity.", "test_family_09_behavior"),
    DNAInvariant(38, "F-M05-09", "component replacement/split/merge requires explicit governed semantics.", "test_family_09_behavior"),
    DNAInvariant(39, "F-M05-09", "derived LOD/proxy fragments do not become new persistent components by default.", "test_family_09_behavior"),
    DNAInvariant(40, "F-M05-09", "CharacterDNA cannot treat pose/expression/camera/light as persistent identity by default.", "test_family_09_behavior"),
    DNAInvariant(41, "F-M05-09", "CharacterDNA cannot seize M39 acting/digital-human production authority.", "test_family_09_behavior"),
    DNAInvariant(42, "F-M05-09", "CreatureDNA cannot require human anatomy or fixed human component slots.", "test_family_09_behavior"),
    DNAInvariant(43, "F-M05-10", "species/archetype identity cannot imply creature individual identity.", "test_family_10_behavior"),
    DNAInvariant(44, "F-M05-10", "ObjectDNA separates persistent form/components from contextual scene state.", "test_family_10_behavior"),
    DNAInvariant(45, "F-M05-08", "Product family/model/SKU/package/physical-instance identity levels cannot be collapsed implicitly.", "test_family_08_behavior"),
    DNAInvariant(46, "F-M05-10", "SKU/GTIN/MPN/serial refs are external mappings, not universal DNA IDs.", "test_family_10_behavior"),
    DNAInvariant(47, "F-M05-10", "Product variant changes declare inherited and overridden trait surfaces.", "test_family_10_behavior"),
    DNAInvariant(48, "F-M05-10", "M46 remains Brand & IP Studio production/brand authority.", "test_family_10_behavior"),
    DNAInvariant(49, "F-M05-10", "EnvironmentDNA cannot silently absorb M04 SceneIR representation authority.", "test_family_10_behavior"),
    DNAInvariant(50, "F-M05-10", "weather/time/camera/lighting are contextual environment state unless explicitly identity-defining.", "test_family_10_behavior"),
    DNAInvariant(51, "F-M05-11", "environment topology/landmark identity must be represented as typed traits/relations, not file paths.", "test_family_11_behavior"),
    DNAInvariant(52, "F-M05-11", "persistent appearance is distinct from contextual appearance and observations.", "test_family_11_behavior"),
    DNAInvariant(53, "F-M05-11", "renderer/provider/model differences cannot redefine persistent appearance automatically.", "test_family_11_behavior"),
    DNAInvariant(54, "F-M05-11", "family reclassification requires explicit migration/projection semantics.", "test_family_11_behavior"),
    DNAInvariant(55, "F-M05-07", "cross-family generic projection cannot rewrite canonical source-family identity.", "test_family_07_behavior"),
    DNAInvariant(56, "F-M05-07", "family extensions use versioned namespaces and fail closed for unknown mandatory semantics.", "test_family_07_behavior"),
    DNAInvariant(57, "F-M05-07", "family-specific traits preserve S01 provenance/policy reachability.", "test_family_07_behavior"),
    DNAInvariant(58, "F-M05-07", "downstream provider scarcity cannot downgrade family-specific identity protections.", "test_family_07_behavior"),
    DNAInvariant(59, "F-M05-21", "family/profile changes participate in deterministic canonical fingerprint/change-surface evidence.", "test_family_21_behavior"),
    DNAInvariant(60, "F-M05-25", "HIVE/agents may propose family classification but cannot canonically reclassify DNA without authority.", "test_family_25_behavior"),
    DNAInvariant(61, "F-M05-12", "M05 owns cross-modal identity linkage, not MotionDNA/VoiceDNA/BrandDNA domain contents.", "test_family_12_behavior"),
    DNAInvariant(62, "F-M05-13", "M30 remains sole MotionDNA/motion-production authority.", "test_family_13_behavior"),
    DNAInvariant(63, "F-M05-13", "M40 remains sole VoiceDNA/voice-production authority.", "test_family_13_behavior"),
    DNAInvariant(64, "F-M05-13", "M46 remains sole BrandDNA/Brand & IP Studio authority.", "test_family_13_behavior"),
    DNAInvariant(65, "F-M05-12", "M45 Campaign DNA/Creative Genome cannot be relabelled as BrandDNA.", "test_family_12_behavior"),
    DNAInvariant(66, "F-M05-14", "M43 remains narrative Canon authority.", "test_family_14_behavior"),
    DNAInvariant(67, "F-M05-14", "M04 SceneIR snapshot cannot silently become persistent SceneIdentityDNA.", "test_family_14_behavior"),
    DNAInvariant(68, "F-M05-12", "SceneIdentityDNA cannot become narrative scene/canon truth.", "test_family_12_behavior"),
    DNAInvariant(69, "F-M05-14", "SceneIdentityDNA member identity is explicit through stable role/member refs.", "test_family_14_behavior"),
    DNAInvariant(70, "F-M05-19", "role-slot substitution requires explicit substitution policy.", "test_family_19_behavior"),
    DNAInvariant(71, "F-M05-14", "LinkedDomainDNARef must identify owner module, family and pinned revision/version.", "test_family_14_behavior"),
    DNAInvariant(72, "F-M05-12", "canonical external DNA links cannot use implicit \"latest\".", "test_family_12_behavior"),
    DNAInvariant(73, "F-M05-14", "external domain DNA advancement cannot mutate an existing M05 revision.", "test_family_14_behavior"),
    DNAInvariant(74, "F-M05-14", "stale required external DNA links fail closed or require explicit review policy.", "test_family_14_behavior"),
    DNAInvariant(75, "F-M05-15", "MotionDNALink cannot canonicalize animation curves, mocap payloads, rigs or current pose.", "test_family_15_behavior"),
    DNAInvariant(76, "F-M05-15", "one motion clip/provider ID cannot define MotionDNA identity.", "test_family_15_behavior"),
    DNAInvariant(77, "F-M05-12", "VoiceDNALink cannot canonicalize provider voice IDs/model weights as persona identity.", "test_family_12_behavior"),
    DNAInvariant(78, "F-M05-12", "VoiceDNA similarity/voiceprints remain evidence unless their owning policy explicitly admits a reference.", "test_family_12_behavior"),
    DNAInvariant(79, "F-M05-15", "generic M05 identity does not require biometric authentication.", "test_family_15_behavior"),
    DNAInvariant(80, "F-M05-15", "BrandDNALink association is explicit and versioned.", "test_family_15_behavior"),
    DNAInvariant(81, "F-M05-15", "brand-link change is identity-breaking only when M05 trait/policy says so.", "test_family_15_behavior"),
    DNAInvariant(82, "F-M05-12", "CrossModalIdentityBinding cannot grant linked modules canonical mutation authority over M05.", "test_family_12_behavior"),
    DNAInvariant(83, "F-M05-12", "cross-modal obligations declare required/optional participants explicitly.", "test_family_12_behavior"),
    DNAInvariant(84, "F-M05-12", "missing required linked DNA cannot disappear silently during projection.", "test_family_12_behavior"),
    DNAInvariant(85, "F-M05-13", "cross-modal consistency expectation is typed, not inferred from similarity.", "test_family_13_behavior"),
    DNAInvariant(86, "F-M05-13", "M01/evaluator owners retain quality and acceptance authority for cross-modal evidence.", "test_family_13_behavior"),
    DNAInvariant(87, "F-M05-13", "CrossModalDNAGraph cannot duplicate M02 Production Graph ownership.", "test_family_13_behavior"),
    DNAInvariant(88, "F-M05-15", "CrossModalDNAGraph cannot duplicate M04 scene graph or M43 Canon Graph ownership.", "test_family_15_behavior"),
    DNAInvariant(89, "F-M05-12", "future domain DNA families use versioned owner/family refs and unknown mandatory families fail closed.", "test_family_12_behavior"),
    DNAInvariant(90, "F-M05-25", "HIVE/agents may retrieve/propose cross-modal links but cannot admit or rewrite canonical links directly.", "test_family_25_behavior"),
    DNAInvariant(91, "F-M05-04", "anchor authority class is explicit and cannot be upgraded by similarity/confidence alone.", "test_family_04_behavior"),
    DNAInvariant(92, "F-M05-04", "anchor lifecycle changes preserve immutable historical evidence.", "test_family_04_behavior"),
    DNAInvariant(93, "F-M05-04", "canonical anchor rebind/revoke requires explicit authority/policy.", "test_family_04_behavior"),
    DNAInvariant(94, "F-M05-03", "observation/proposed anchors cannot mutate canonical identity.", "test_family_03_behavior"),
    DNAInvariant(95, "F-M05-16", "drift evidence is path-level and typed.", "test_family_16_behavior"),
    DNAInvariant(96, "F-M05-16", "identity drift cannot be represented solely by one scalar score.", "test_family_16_behavior"),
    DNAInvariant(97, "F-M05-16", "missing/unknown evidence cannot be treated as pass.", "test_family_16_behavior"),
    DNAInvariant(98, "F-M05-16", "identity-defining failures cannot be averaged away by aggregate scores.", "test_family_16_behavior"),
    DNAInvariant(99, "F-M05-16", "drift findings preserve uncertainty and evaluator ownership.", "test_family_16_behavior"),
    DNAInvariant(100, "F-M05-16", "drift evidence cannot self-admit a canonical mutation.", "test_family_16_behavior"),
    DNAInvariant(101, "F-M05-17", "representation repair cannot rewrite canonical DNA.", "test_family_17_behavior"),
    DNAInvariant(102, "F-M05-17", "contextual variation does not require DNA mutation when policy allows it.", "test_family_17_behavior"),
    DNAInvariant(103, "F-M05-17", "DNAMutationProposal is noncanonical until an explicit decision admits it.", "test_family_17_behavior"),
    DNAInvariant(104, "F-M05-17", "mutation proposals identify exact source revision and typed change surface.", "test_family_17_behavior"),
    DNAInvariant(105, "F-M05-17", "protected trait mutation requires explicit policy/authority.", "test_family_17_behavior"),
    DNAInvariant(106, "F-M05-18", "downstream model/provider output cannot silently authorize mutation.", "test_family_18_behavior"),
    DNAInvariant(107, "F-M05-18", "IdentityMutationDecision authority is explicit and policy-bound.", "test_family_18_behavior"),
    DNAInvariant(108, "F-M05-18", "same-identity admitted mutation creates a new immutable DNA revision.", "test_family_18_behavior"),
    DNAInvariant(109, "F-M05-05", "identity break creates a new stable dna_id rather than rewriting the original.", "test_family_05_behavior"),
    DNAInvariant(110, "F-M05-05", "identity-break lineage to source revision remains explicit.", "test_family_05_behavior"),
    DNAInvariant(111, "F-M05-16", "identity split preserves source history and explicit allocation of traits/components/links.", "test_family_16_behavior"),
    DNAInvariant(112, "F-M05-16", "identity consolidation/equivalence never erases source IDs/history.", "test_family_16_behavior"),
    DNAInvariant(113, "F-M05-19", "similarity threshold alone cannot merge identities.", "test_family_19_behavior"),
    DNAInvariant(114, "F-M05-16", "IdentityContinuityEnvelope is separate from M01 quality/Fidelity authority.", "test_family_16_behavior"),
    DNAInvariant(115, "F-M05-19", "M37 temporal continuity evidence cannot mutate canonical M05 DNA.", "test_family_19_behavior"),
    DNAInvariant(116, "F-M05-16", "M39 digital-human persona/runtime cannot create a competing generic identity root.", "test_family_16_behavior"),
    DNAInvariant(117, "F-M05-16", "sensitive drift evidence may remain restricted references rather than canonical payload copies.", "test_family_16_behavior"),
    DNAInvariant(118, "F-M05-16", "M53/M54 retain rights/consent/provenance/security authority over protected identity evidence.", "test_family_16_behavior"),
    DNAInvariant(119, "F-M05-17", "drift/transition reports are deterministic and fingerprintable without embedding private evidence payloads.", "test_family_17_behavior"),
    DNAInvariant(120, "F-M05-25", "HIVE/agents may detect/propose drift or mutation but cannot directly admit protected canonical identity changes.", "test_family_25_behavior"),
    DNAInvariant(121, "F-M05-20", "M05 lineage relations cannot create or replace M02 project/production branches.", "test_family_20_behavior"),
    DNAInvariant(122, "F-M05-20", "M02 remains branch/snapshot/rollback authority.", "test_family_20_behavior"),
    DNAInvariant(123, "F-M05-20", "M06 operational persistence/reconstruction/versioning must implement M02 semantic build/version/rollback contracts rather than create competing authority.", "test_family_20_behavior"),
    DNAInvariant(124, "F-M05-21", "build/master/content hashes cannot become persistent dna_id automatically.", "test_family_21_behavior"),
    DNAInvariant(125, "F-M05-21", "DNA compatibility is directional.", "test_family_21_behavior"),
    DNAInvariant(126, "F-M05-21", "DNA compatibility is multi-axis and cannot be proven by version number alone.", "test_family_21_behavior"),
    DNAInvariant(127, "F-M05-21", "compatibility outcome preserves unknown/indeterminate distinct from compatible.", "test_family_21_behavior"),
    DNAInvariant(128, "F-M05-21", "lossy compatibility must be explicit.", "test_family_21_behavior"),
    DNAInvariant(129, "F-M05-21", "DNAMigrationPlan declares transformed/preserved/dropped/defaulted paths.", "test_family_21_behavior"),
    DNAInvariant(130, "F-M05-21", "migration loss cannot be hidden.", "test_family_21_behavior"),
    DNAInvariant(131, "F-M05-22", "migration cannot silently convert identity break into same-identity continuation.", "test_family_22_behavior"),
    DNAInvariant(132, "F-M05-22", "unknown mandatory schema/extension semantics fail closed during migration/import.", "test_family_22_behavior"),
    DNAInvariant(133, "F-M05-22", "reusable package ID/version is distinct from subject dna_id/revision.", "test_family_22_behavior"),
    DNAInvariant(134, "F-M05-22", "repackaging cannot redefine subject identity by itself.", "test_family_22_behavior"),
    DNAInvariant(135, "F-M05-22", "a package may contain multiple DNA identities only when explicitly declared.", "test_family_22_behavior"),
    DNAInvariant(136, "F-M05-22", "package dependency closure distinguishes required and optional dependencies.", "test_family_22_behavior"),
    DNAInvariant(137, "F-M05-23", "missing required package dependency fails closed.", "test_family_23_behavior"),
    DNAInvariant(138, "F-M05-19", "marketplace contract cannot self-authorize rights/license/consent.", "test_family_19_behavior"),
    DNAInvariant(139, "F-M05-19", "M53 remains rights/license/consent/provenance authority.", "test_family_19_behavior"),
    DNAInvariant(140, "F-M05-23", "package security classification cannot self-prove safety.", "test_family_23_behavior"),
    DNAInvariant(141, "F-M05-23", "M54 remains security/restricted-content/permission authority.", "test_family_23_behavior"),
    DNAInvariant(142, "F-M05-24", "M55 remains storage/CAS/cache/archive authority.", "test_family_24_behavior"),
    DNAInvariant(143, "F-M05-24", "M59 remains concrete export/publishing/delivery authority.", "test_family_24_behavior"),
    DNAInvariant(144, "F-M05-24", "import parsing/validation cannot overwrite existing canonical DNA silently.", "test_family_24_behavior"),
    DNAInvariant(145, "F-M05-19", "imported identity collision/equivalence routes through governed S04 semantics.", "test_family_19_behavior"),
    DNAInvariant(146, "F-M05-23", "restricted biometric/private evidence is referenced/minimized unless explicit policy permits inclusion.", "test_family_23_behavior"),
    DNAInvariant(147, "F-M05-19", "canonical reusable DNA package requires no arbitrary executable code.", "test_family_19_behavior"),
    DNAInvariant(148, "F-M05-24", "deprecation/retirement never rewrites historical package/DNA revisions.", "test_family_24_behavior"),
    DNAInvariant(149, "F-M05-21", "conformance report proves contract/schema conformance, not legal rights or semantic identity equivalence by itself.", "test_family_21_behavior"),
    DNAInvariant(150, "F-M05-25", "HIVE/agents may discover/package/propose compatibility but cannot directly admit imported canonical identity or protected mutations.", "test_family_25_behavior"),
)


def invariants_for_family(family: str) -> tuple[DNAInvariant, ...]:
    return tuple(item for item in M05_INVARIANTS if item.family == family)


def validate_invariant_catalog() -> None:
    numbers = [item.number for item in M05_INVARIANTS]
    families = {item.family for item in M05_INVARIANTS}
    expected = {f"F-M05-{number:02d}" for number in range(1, 26)}
    if numbers != list(range(1, 151)) or families != expected:
        raise DNAIntegrityError("M05 invariant catalog must map all 150 hard invariants exactly once to all 25 families")
    if any(not item.statement or not item.proof_method for item in M05_INVARIANTS):
        raise DNAIntegrityError("each frozen M05 invariant requires a statement and behavioral proof target")
