"""Traceable registry of the 150 frozen M06 hard invariants."""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType

from .errors import ProductionStateIntegrityError

__all__ = [
    "InvariantRequirement",
    "M06_INVARIANTS",
    "M06_INVARIANT_MAP",
    "validate_invariant_catalog",
]


@dataclass(frozen=True)
class InvariantRequirement:
    number: int
    section: str
    statement: str
    proof_target: str


M06_INVARIANTS = (
    InvariantRequirement(1, "S01", "Content digests are never semantic identity.", "test_family_rvf"),
    InvariantRequirement(2, "S01", "M05 dna_id is never derived automatically from M06/M55 content hashes.", "test_family_rvf"),
    InvariantRequirement(3, "S01", "M06 operational revisions never replace M02 semantic revisions/snapshots.", "test_family_rvf"),
    InvariantRequirement(4, "S01", "M06 never creates a competing branch/lifecycle authority.", "test_family_rvf"),
    InvariantRequirement(5, "S01", "Historical admitted revision manifests are immutable.", "test_family_rvf"),
    InvariantRequirement(6, "S01", "Historical masters are immutable.", "test_family_rvf"),
    InvariantRequirement(7, "S01", "Supersession creates new history.", "test_family_iml"),
    InvariantRequirement(8, "S01", "Paths/names/URLs/provider IDs/storage locators are not canonical identity.", "test_family_iml"),
    InvariantRequirement(9, "S01", "Digest algorithm and version are explicit.", "test_family_iml"),
    InvariantRequirement(10, "S01", "Unknown digest algorithms fail closed for mandatory verification.", "test_family_iml"),
    InvariantRequirement(11, "S01", "Digest equality alone never proves semantic equivalence.", "test_family_iml"),
    InvariantRequirement(12, "S01", "Digest equality alone never proves quality, rights, security or acceptance.", "test_family_iml"),
    InvariantRequirement(13, "S01", "Same bytes may represent distinct semantic artifacts.", "test_family_das"),
    InvariantRequirement(14, "S01", "Different bytes cannot be silently substituted under an immutable materialization ref.", "test_family_das"),
    InvariantRequirement(15, "S01", "Required dependency refs are exact/versioned and never implicit-latest.", "test_family_das"),
    InvariantRequirement(16, "S01", "Unknown mandatory dependency state fails closed.", "test_family_das"),
    InvariantRequirement(17, "S01", "Missing, unknown and corrupt are distinct.", "test_family_das"),
    InvariantRequirement(18, "S01", "Physical availability is distinct from semantic validity.", "test_family_das"),
    InvariantRequirement(19, "S01", "Attempt success cannot promote an immutable master by itself.", "test_family_sea"),
    InvariantRequirement(20, "S01", "Master admission consumes M02/M01 authority rather than replacing it.", "test_family_sea"),
    InvariantRequirement(21, "S01", "Rights/provenance/consent authority remains M53.", "test_family_sea"),
    InvariantRequirement(22, "S01", "Security/restricted-content authority remains M54.", "test_family_sea"),
    InvariantRequirement(23, "S01", "Physical CAS/storage/cache/archive authority remains M55.", "test_family_sea"),
    InvariantRequirement(24, "S01", "Storage deduplication cannot collapse semantic history.", "test_family_sea"),
    InvariantRequirement(25, "S01", "Storage movement/tiering cannot alter revision identity.", "test_family_avs"),
    InvariantRequirement(26, "S01", "Re-encoding that changes canonical bytes produces explicit new materialization history.", "test_family_avs"),
    InvariantRequirement(27, "S01", "Repair cannot rewrite an admitted master in place.", "test_family_avs"),
    InvariantRequirement(28, "S01", "Restoration from archive must verify declared integrity before admission as available.", "test_family_avs"),
    InvariantRequirement(29, "S01", "Unknown/indeterminate evidence cannot be coerced to PASS.", "test_family_avs"),
    InvariantRequirement(30, "S01", "HIVE/agents may observe/propose persistence actions but cannot rewrite canonical M02/M06 history directly.", "test_family_avs"),
    InvariantRequirement(31, "S02", "M06 dependency observations cannot silently redefine M02 graph semantics.", "test_family_cfm"),
    InvariantRequirement(32, "S02", "Observed material hidden dependencies cannot be discarded silently.", "test_family_cfm"),
    InvariantRequirement(33, "S02", "Dependency fingerprints are versioned and schema-qualified.", "test_family_cfm"),
    InvariantRequirement(34, "S02", "Fingerprints bind exact refs rather than implicit latest.", "test_family_cfm"),
    InvariantRequirement(35, "S02", "Fingerprint scope is explicit.", "test_family_cfm"),
    InvariantRequirement(36, "S02", "Different fingerprint scopes cannot be treated as equivalent automatically.", "test_family_cfm"),
    InvariantRequirement(37, "S02", "Storage locator changes are non-material unless an admitted semantic contract says otherwise.", "test_family_msi"),
    InvariantRequirement(38, "S02", "Display-name/path changes cannot invalidate semantic work by default.", "test_family_msi"),
    InvariantRequirement(39, "S02", "A content hash alone is insufficient as a complete causal fingerprint.", "test_family_msi"),
    InvariantRequirement(40, "S02", "Dependency slices/facets must preserve their M02 meaning.", "test_family_msi"),
    InvariantRequirement(41, "S02", "Unknown mandatory dependency state blocks safe reuse.", "test_family_msi"),
    InvariantRequirement(42, "S02", "Unknown materiality cannot be coerced to non-material.", "test_family_msi"),
    InvariantRequirement(43, "S02", "Absence from a partial reverse index cannot prove unaffected.", "test_family_hds"),
    InvariantRequirement(44, "S02", "Reverse dependency indexes are derived/rebuildable operational state.", "test_family_hds"),
    InvariantRequirement(45, "S02", "Index corruption cannot authorize reuse.", "test_family_hds"),
    InvariantRequirement(46, "S02", "Impact analysis must expose direct and transitive causal paths.", "test_family_hds"),
    InvariantRequirement(47, "S02", "Impact analysis must preserve an unknown frontier.", "test_family_hds"),
    InvariantRequirement(48, "S02", "`UNAFFECTED_PROVEN` requires positive sufficient evidence.", "test_family_hds"),
    InvariantRequirement(49, "S02", "Affected and potentially affected are distinct.", "test_family_icx"),
    InvariantRequirement(50, "S02", "Stale evidence cannot prove unaffected.", "test_family_icx"),
    InvariantRequirement(51, "S02", "Hidden dependency discovery invalidates incompatible prior reuse assumptions.", "test_family_icx"),
    InvariantRequirement(52, "S02", "Dependency discovery creates new evidence/history rather than rewriting old receipts.", "test_family_icx"),
    InvariantRequirement(53, "S02", "Dynamic dependency discovery must be bounded and explicit.", "test_family_icx"),
    InvariantRequirement(54, "S02", "Wildcards cannot falsely claim complete dependency closure.", "test_family_icx"),
    InvariantRequirement(55, "S02", "Policy/rights/security refs may be material to admissibility without being media bytes.", "test_family_rdi"),
    InvariantRequirement(56, "S02", "M05 identity-sensitive refs may invalidate consumers without transferring identity authority to M06.", "test_family_rdi"),
    InvariantRequirement(57, "S02", "Toolchain/environment facts affect fingerprints only when declared materially relevant.", "test_family_rdi"),
    InvariantRequirement(58, "S02", "Hardware/performance changes cannot silently change semantic dependency truth.", "test_family_rdi"),
    InvariantRequirement(59, "S02", "Impact receipts are analysis evidence, not execution/promotion authority.", "test_family_rdi"),
    InvariantRequirement(60, "S02", "HIVE/agents may suggest dependency relationships but cannot self-admit them as canonical material dependencies.", "test_family_rdi"),
    InvariantRequirement(61, "S03", "Selective rebuild decisions must map to M02 build semantics.", "test_family_sre"),
    InvariantRequirement(62, "S03", "Cache presence alone never authorizes reuse.", "test_family_sre"),
    InvariantRequirement(63, "S03", "Content digest equality alone never authorizes semantic reuse.", "test_family_sre"),
    InvariantRequirement(64, "S03", "Reuse requires positive evidence for all mandatory material dimensions.", "test_family_sre"),
    InvariantRequirement(65, "S03", "Unknown mandatory reuse evidence blocks reuse.", "test_family_sre"),
    InvariantRequirement(66, "S03", "Reuse receipts bind exact revisions/materializations.", "test_family_sre"),
    InvariantRequirement(67, "S03", "Reuse admission is scoped to one decision and does not authorize future reuse automatically.", "test_family_rap"),
    InvariantRequirement(68, "S03", "Stale quality/policy evidence cannot be silently reused when materially invalidated.", "test_family_rap"),
    InvariantRequirement(69, "S03", "Partial rebuild requires an admitted rebuild boundary.", "test_family_rap"),
    InvariantRequirement(70, "S03", "Unknown rebuild boundaries escalate conservatively.", "test_family_rap"),
    InvariantRequirement(71, "S03", "A partial rebuild declares both rebuilt and reused ancestry.", "test_family_rap"),
    InvariantRequirement(72, "S03", "Recomposition rules are explicit/versioned.", "test_family_rap"),
    InvariantRequirement(73, "S03", "Recomposition cannot silently weaken protected identity constraints.", "test_family_fex"),
    InvariantRequirement(74, "S03", "Recomposition cannot silently lower M01-required final quality.", "test_family_fex"),
    InvariantRequirement(75, "S03", "Dirty frontier minimization occurs only after correctness proof.", "test_family_fex"),
    InvariantRequirement(76, "S03", "Frontier expansion is conservative when uncertainty increases.", "test_family_fex"),
    InvariantRequirement(77, "S03", "A less conservative disposition requires stronger evidence.", "test_family_fex"),
    InvariantRequirement(78, "S03", "`NO_WORK_PROVEN` requires positive proof.", "test_family_fex"),
    InvariantRequirement(79, "S03", "`VERIFY_ONLY` cannot be converted to no-work without successful required verification.", "test_family_mxr"),
    InvariantRequirement(80, "S03", "Failed/incomplete outputs cannot become admitted masters.", "test_family_mxr"),
    InvariantRequirement(81, "S03", "Interrupted work cannot mutate an existing admitted master.", "test_family_mxr"),
    InvariantRequirement(82, "S03", "Resume requires unchanged material causal bindings.", "test_family_mxr"),
    InvariantRequirement(83, "S03", "Material input change invalidates incompatible resume state.", "test_family_mxr"),
    InvariantRequirement(84, "S03", "Retry, resume, repair and rebuild remain distinct operations.", "test_family_mxr"),
    InvariantRequirement(85, "S03", "Stochastic fingerprint equality cannot claim byte-identical replay.", "test_family_sre"),
    InvariantRequirement(86, "S03", "Reuse class explicitly states the equivalence guarantee.", "test_family_sre"),
    InvariantRequirement(87, "S03", "Seeds/parameters cannot turn stochastic work into falsely deterministic history.", "test_family_sre"),
    InvariantRequirement(88, "S03", "M49 remains repair execution authority.", "test_family_sre"),
    InvariantRequirement(89, "S03", "Repair creates new history and preserves ancestry.", "test_family_sre"),
    InvariantRequirement(90, "S03", "HIVE/agents may propose selective work but cannot self-admit unsafe reuse or promotion.", "test_family_sre"),
    InvariantRequirement(91, "S04", "Reproducibility is an explicit class, not a boolean shortcut.", "test_family_sds"),
    InvariantRequirement(92, "S04", "Stronger reproducibility cannot be inferred from weaker evidence.", "test_family_sds"),
    InvariantRequirement(93, "S04", "Reconstruction manifests bind exact/versioned refs, never implicit latest.", "test_family_sds"),
    InvariantRequirement(94, "S04", "Admitted reconstruction manifests are immutable.", "test_family_sds"),
    InvariantRequirement(95, "S04", "Reproducibility receipts record achieved evidence, not intended claims.", "test_family_sds"),
    InvariantRequirement(96, "S04", "A seed alone never proves deterministic replay.", "test_family_rcl"),
    InvariantRequirement(97, "S04", "Fingerprint equality alone never proves exact-byte replay.", "test_family_rcl"),
    InvariantRequirement(98, "S04", "Exact-byte claims require all materially byte-affecting dimensions to be pinned/verified.", "test_family_rcl"),
    InvariantRequirement(99, "S04", "Unpinned mutable provider/model/workflow dependencies prevent unjustified exact replay.", "test_family_rcl"),
    InvariantRequirement(100, "S04", "Runtime/hardware nondeterminism must be represented when materially relevant.", "test_family_rcl"),
    InvariantRequirement(101, "S04", "Exact semantic reconstruction is distinct from exact-byte reconstruction.", "test_family_rxm"),
    InvariantRequirement(102, "S04", "Equivalence reconstruction requires an explicit versioned equivalence contract.", "test_family_rxm"),
    InvariantRequirement(103, "S04", "M06 cannot invent domain equivalence criteria owned by later evaluators.", "test_family_rxm"),
    InvariantRequirement(104, "S04", "M01 quality authority remains external to reconstruction truth.", "test_family_rxm"),
    InvariantRequirement(105, "S04", "M05 protected identity authority remains external to reconstruction truth.", "test_family_rxm"),
    InvariantRequirement(106, "S04", "Historical external dependencies require immutable/versioned evidence where available.", "test_family_drg"),
    InvariantRequirement(107, "S04", "URLs/provider names/paths cannot serve as historical identity by themselves.", "test_family_drg"),
    InvariantRequirement(108, "S04", "Missing historical dependencies cannot be silently replaced.", "test_family_drg"),
    InvariantRequirement(109, "S04", "Restoration from retained materialization is distinct from regeneration.", "test_family_drg"),
    InvariantRequirement(110, "S04", "Restoration still verifies declared integrity.", "test_family_drg"),
    InvariantRequirement(111, "S04", "Reconstruction attempts create new evidence and never rewrite historical receipts.", "test_family_esb"),
    InvariantRequirement(112, "S04", "Divergence states remain explicit.", "test_family_esb"),
    InvariantRequirement(113, "S04", "Byte divergence and semantic divergence are distinct.", "test_family_esb"),
    InvariantRequirement(114, "S04", "Unknown divergence cannot be coerced to success.", "test_family_esb"),
    InvariantRequirement(115, "S04", "Failed equivalence cannot be hidden by successful execution.", "test_family_esb"),
    InvariantRequirement(116, "S04", "Current rights/security controls cannot be bypassed by historical permission.", "test_family_hpr"),
    InvariantRequirement(117, "S04", "Historical execution permission does not imply current permission.", "test_family_hpr"),
    InvariantRequirement(118, "S04", "Reconstructed outputs cannot overwrite immutable masters.", "test_family_hpr"),
    InvariantRequirement(119, "S04", "Reconstructed outputs require normal promotion/quality gates before becoming accepted masters.", "test_family_hpr"),
    InvariantRequirement(120, "S04", "HIVE/agents may propose reconstruction plans but cannot self-certify reproducibility or equivalence.", "test_family_hpr"),
    InvariantRequirement(121, "S05", "Operational rollback creates new history and never rewrites historical state.", "test_family_lrg"),
    InvariantRequirement(122, "S05", "Rollback targets exact M02 snapshots/revisions, never implicit latest.", "test_family_lrg"),
    InvariantRequirement(123, "S05", "Rollback outcome cannot claim a stronger reproducibility class than S04 evidence proves.", "test_family_lrg"),
    InvariantRequirement(124, "S05", "Historical masters remain immutable during rollback.", "test_family_lrg"),
    InvariantRequirement(125, "S05", "Current rights/security controls apply to rollback/recovery.", "test_family_lrg"),
    InvariantRequirement(126, "S05", "Rollback failure cannot corrupt the current admitted state.", "test_family_lrg"),
    InvariantRequirement(127, "S05", "Partial recovery is explicit and cannot masquerade as complete rollback.", "test_family_sgc"),
    InvariantRequirement(128, "S05", "Cleanup requires positive proof of non-reachability from all protected closures.", "test_family_sgc"),
    InvariantRequirement(129, "S05", "Unknown reachability is not safe to delete.", "test_family_sgc"),
    InvariantRequirement(130, "S05", "Partial/stale reverse indexes cannot authorize deletion.", "test_family_sgc"),
    InvariantRequirement(131, "S05", "Retention pins override cleanup eligibility where applicable.", "test_family_sgc"),
    InvariantRequirement(132, "S05", "Cleanup cannot break required historical reconstruction guarantees silently.", "test_family_sgc"),
    InvariantRequirement(133, "S05", "M05 identity/history refs required by protected lineage cannot be discarded silently.", "test_family_rrb"),
    InvariantRequirement(134, "S05", "S03 reused ancestry participates in cleanup reachability.", "test_family_rrb"),
    InvariantRequirement(135, "S05", "S04 reconstruction closure participates in cleanup reachability.", "test_family_rrb"),
    InvariantRequirement(136, "S05", "Logical retirement is distinct from physical deletion.", "test_family_rrb"),
    InvariantRequirement(137, "S05", "M55 remains physical deletion/storage-GC authority.", "test_family_rrb"),
    InvariantRequirement(138, "S05", "Deletion authorization and deletion completion are separate receipts.", "test_family_rrb"),
    InvariantRequirement(139, "S05", "Failed deletion cannot be recorded as completed deletion.", "test_family_rsc"),
    InvariantRequirement(140, "S05", "Cleanup receipts bind exact lineage/reachability evidence.", "test_family_rsc"),
    InvariantRequirement(141, "S05", "Stale cleanup authorization requires revalidation after material lineage changes.", "test_family_rsc"),
    InvariantRequirement(142, "S05", "Concurrent protection/reachability changes cannot be ignored by deletion execution.", "test_family_rsc"),
    InvariantRequirement(143, "S05", "Release operational closure binds exact immutable refs.", "test_family_rsc"),
    InvariantRequirement(144, "S05", "A released closure cannot follow mutable implicit-latest dependencies.", "test_family_rsc"),
    InvariantRequirement(145, "S05", "M06 cannot self-promote a release.", "test_family_cra"),
    InvariantRequirement(146, "S05", "M59 remains publishing/delivery authority.", "test_family_cra"),
    InvariantRequirement(147, "S05", "Release corrections create new history and explicit supersession.", "test_family_cra"),
    InvariantRequirement(148, "S05", "Mutable aliases cannot rewrite historical release identity.", "test_family_cra"),
    InvariantRequirement(149, "S05", "Archive tier/location does not define production/revision identity.", "test_family_cra"),
    InvariantRequirement(150, "S05", "HIVE/agents may propose rollback/cleanup/release actions but cannot self-authorize protected deletion, rollback promotion or release.", "test_family_cra"),
)

M06_INVARIANT_MAP = MappingProxyType({item.number: item for item in M06_INVARIANTS})


def validate_invariant_catalog() -> None:
    numbers = tuple(item.number for item in M06_INVARIANTS)
    if numbers != tuple(range(1, 151)) or len(M06_INVARIANT_MAP) != 150:
        raise ProductionStateIntegrityError("M06 hard invariants must be numbered exactly 1 through 150")
    if any(not item.statement or item.section not in {"S01", "S02", "S03", "S04", "S05"} or not item.proof_target for item in M06_INVARIANTS):
        raise ProductionStateIntegrityError("every M06 invariant requires a statement, section and executable proof target")
