"""Closed vocabularies for M07 hardware and runtime evidence."""

from __future__ import annotations

from enum import Enum

__all__ = [
    "ObservationState", "FreshnessClass", "EvidenceStrength", "SubjectKind", "RuntimeScope",
    "PrivacyClass", "ProbePermissionClass", "ProbeOrigin", "ProbeInterface", "BackendFamily",
    "VersionDimension", "ConfidenceLevel", "ConfidenceAxis", "CapabilityDimension",
    "PrecisionFamily", "MediaDirection", "MemoryKind", "TopologyNodeKind", "TopologyRelation",
    "MetricSemantics", "PressureState", "ChangeClass", "CompatibilityLevel", "MigrationOperation",
    "ExtensionDisposition",
]


class ObservationState(str, Enum):
    OBSERVED = "OBSERVED"
    NOT_PRESENT_PROVEN = "NOT_PRESENT_PROVEN"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED_PROBE = "UNSUPPORTED_PROBE"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    UNAVAILABLE = "UNAVAILABLE"
    CONFLICTING = "CONFLICTING"
    STALE = "STALE"
    PARTIAL = "PARTIAL"


class FreshnessClass(str, Enum):
    BOOT_STABLE = "BOOT_STABLE"
    INSTALL_STABLE = "INSTALL_STABLE"
    TOPOLOGY_STABLE = "TOPOLOGY_STABLE"
    DYNAMIC = "DYNAMIC"
    UNKNOWN_VOLATILITY = "UNKNOWN_VOLATILITY"


class EvidenceStrength(str, Enum):
    DECLARED = "DECLARED"
    LOADABLE = "LOADABLE"
    DEVICE_BOUND = "DEVICE_BOUND"
    FEATURE_REPORTED = "FEATURE_REPORTED"
    SMOKE_VERIFIED = "SMOKE_VERIFIED"


class SubjectKind(str, Enum):
    PHYSICAL = "PHYSICAL"
    LOGICAL = "LOGICAL"
    VIRTUAL = "VIRTUAL"
    PARTITION = "PARTITION"
    HOST_RESOURCE = "HOST_RESOURCE"


class RuntimeScope(str, Enum):
    HOST = "HOST"
    PROCESS = "PROCESS"
    CONTAINER = "CONTAINER"
    VM = "VM"
    WSL = "WSL"
    SANDBOX = "SANDBOX"


class PrivacyClass(str, Enum):
    PUBLIC_FACT = "PUBLIC_FACT"
    LOCAL_IDENTIFIER = "LOCAL_IDENTIFIER"
    SENSITIVE_IDENTIFIER = "SENSITIVE_IDENTIFIER"
    PROCESS_METADATA = "PROCESS_METADATA"


class ProbePermissionClass(str, Enum):
    BASIC_READ = "BASIC_READ"
    DEVICE_ENUMERATION = "DEVICE_ENUMERATION"
    TELEMETRY_READ = "TELEMETRY_READ"
    CONFORMANCE_READ = "CONFORMANCE_READ"


class ProbeOrigin(str, Enum):
    CORE = "CORE"
    GOVERNED_EXTENSION = "GOVERNED_EXTENSION"


class ProbeInterface(str, Enum):
    DECLARED_EVIDENCE = "DECLARED_EVIDENCE"
    OPERATING_SYSTEM_API = "OPERATING_SYSTEM_API"
    VENDOR_RUNTIME_API = "VENDOR_RUNTIME_API"
    STANDARD_RUNTIME_API = "STANDARD_RUNTIME_API"


class BackendFamily(str, Enum):
    CUDA = "CUDA"
    ROCM = "ROCM"
    DIRECTML = "DIRECTML"
    METAL = "METAL"
    CPU = "CPU"
    PORTABLE = "PORTABLE"
    GENERIC = "GENERIC"


class VersionDimension(str, Enum):
    KERNEL_DRIVER = "KERNEL_DRIVER"
    USER_DRIVER = "USER_DRIVER"
    RUNTIME = "RUNTIME"
    LOADER_API = "LOADER_API"
    TOOLKIT_SDK = "TOOLKIT_SDK"
    LIBRARY = "LIBRARY"
    FRAMEWORK_BINDING = "FRAMEWORK_BINDING"
    OS_RUNTIME = "OS_RUNTIME"
    FIRMWARE = "FIRMWARE"


class ConfidenceLevel(str, Enum):
    NONE = "NONE"
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERIFIED = "VERIFIED"


class ConfidenceAxis(str, Enum):
    SOURCE_AUTHORITY = "SOURCE_AUTHORITY"
    SUBJECT_BINDING = "SUBJECT_BINDING"
    EVIDENCE_STRENGTH = "EVIDENCE_STRENGTH"
    FRESHNESS = "FRESHNESS"
    SOURCE_AGREEMENT = "SOURCE_AGREEMENT"
    SEMANTIC_COMPLETENESS = "SEMANTIC_COMPLETENESS"
    VISIBILITY_COMPLETENESS = "VISIBILITY_COMPLETENESS"
    DERIVATION_DEPTH = "DERIVATION_DEPTH"


class CapabilityDimension(str, Enum):
    REPRESENTATION = "REPRESENTATION"
    ARITHMETIC = "ARITHMETIC"
    ACCELERATION_REPORTED = "ACCELERATION_REPORTED"
    ACCUMULATION = "ACCUMULATION"
    CONVERSION = "CONVERSION"
    FRAMEWORK_EXPOSURE = "FRAMEWORK_EXPOSURE"
    CONFORMANCE = "CONFORMANCE"


class PrecisionFamily(str, Enum):
    FP64 = "FP64"
    FP32 = "FP32"
    TF32 = "TF32"
    FP16 = "FP16"
    BF16 = "BF16"
    FP8_E4M3 = "FP8_E4M3"
    FP8_E5M2 = "FP8_E5M2"
    INT64 = "INT64"
    INT32 = "INT32"
    INT16 = "INT16"
    INT8 = "INT8"
    INT4 = "INT4"
    SUBBYTE = "SUBBYTE"


class MediaDirection(str, Enum):
    ENCODE = "ENCODE"
    DECODE = "DECODE"


class MemoryKind(str, Enum):
    DEDICATED_VRAM = "DEDICATED_VRAM"
    SHARED_APERTURE = "SHARED_APERTURE"
    UNIFIED_PHYSICAL = "UNIFIED_PHYSICAL"
    HOST_RAM = "HOST_RAM"
    PROCESS_ADDRESS_SPACE = "PROCESS_ADDRESS_SPACE"
    STORAGE_CAPACITY = "STORAGE_CAPACITY"
    STORAGE_AVAILABLE = "STORAGE_AVAILABLE"


class TopologyNodeKind(str, Enum):
    HOST = "HOST"
    CPU_PACKAGE = "CPU_PACKAGE"
    NUMA_NODE = "NUMA_NODE"
    ACCELERATOR = "ACCELERATOR"
    PARTITION = "PARTITION"
    MEMORY_DOMAIN = "MEMORY_DOMAIN"
    PCI_DEVICE = "PCI_DEVICE"
    STORAGE_DEVICE = "STORAGE_DEVICE"
    VOLUME = "VOLUME"
    MEDIA_ENGINE = "MEDIA_ENGINE"
    RUNTIME_ADAPTER = "RUNTIME_ADAPTER"


class TopologyRelation(str, Enum):
    ATTACHED_TO = "ATTACHED_TO"
    PARENT_OF = "PARENT_OF"
    NUMA_LOCAL_TO = "NUMA_LOCAL_TO"
    SHARES_MEMORY_WITH = "SHARES_MEMORY_WITH"
    PEER_ACCESS_TO = "PEER_ACCESS_TO"
    INTERCONNECT_TO = "INTERCONNECT_TO"
    ROUTED_THROUGH = "ROUTED_THROUGH"
    EXPOSED_AS = "EXPOSED_AS"


class MetricSemantics(str, Enum):
    INSTANTANEOUS_GAUGE = "INSTANTANEOUS_GAUGE"
    CUMULATIVE_COUNTER = "CUMULATIVE_COUNTER"
    MONOTONIC_COUNTER = "MONOTONIC_COUNTER"
    BOUNDED_PERCENTAGE = "BOUNDED_PERCENTAGE"
    REPORTED_LIMIT = "REPORTED_LIMIT"
    CONFIGURED_LIMIT = "CONFIGURED_LIMIT"
    EVENT_FLAG = "EVENT_FLAG"
    DERIVED_VALUE = "DERIVED_VALUE"


class PressureState(str, Enum):
    NORMAL_REPORTED = "NORMAL_REPORTED"
    PRESSURE_REPORTED = "PRESSURE_REPORTED"
    CRITICAL_REPORTED = "CRITICAL_REPORTED"
    UNKNOWN = "UNKNOWN"
    UNAVAILABLE = "UNAVAILABLE"
    CONFLICTING = "CONFLICTING"
    STALE = "STALE"


class ChangeClass(str, Enum):
    IDENTITY = "IDENTITY"
    RUNTIME_SUBSTRATE = "RUNTIME_SUBSTRATE"
    DRIVER_RUNTIME = "DRIVER_RUNTIME"
    CAPABILITY = "CAPABILITY"
    TOPOLOGY = "TOPOLOGY"
    MEMORY_CAPACITY = "MEMORY_CAPACITY"
    MEDIA_PRECISION = "MEDIA_PRECISION"
    TELEMETRY_ONLY = "TELEMETRY_ONLY"
    VISIBILITY_PERMISSION = "VISIBILITY_PERMISSION"
    CONFIDENCE_EVIDENCE = "CONFIDENCE_EVIDENCE"
    SCHEMA_ONLY = "SCHEMA_ONLY"


class CompatibilityLevel(str, Enum):
    PATCH = "PATCH"
    MINOR = "MINOR"
    MAJOR = "MAJOR"


class MigrationOperation(str, Enum):
    ADD_OPTIONAL_EXTENSION = "ADD_OPTIONAL_EXTENSION"
    RENAME_OPTIONAL_EXTENSION = "RENAME_OPTIONAL_EXTENSION"
    DROP_OPTIONAL_EXTENSION = "DROP_OPTIONAL_EXTENSION"
    CLARIFY_METADATA = "CLARIFY_METADATA"


class ExtensionDisposition(str, Enum):
    OPTIONAL_PRESERVE = "OPTIONAL_PRESERVE"
    REQUIRED_KNOWN = "REQUIRED_KNOWN"
    UNKNOWN_REQUIRED = "UNKNOWN_REQUIRED"
