"""Literal proof map for all 235 frozen M07 hard invariants."""

from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType

from .errors import HardwareGenomeIntegrityError

__all__ = ["InvariantRequirement", "M07_INVARIANTS", "M07_INVARIANT_MAP", "validate_invariant_catalog"]


@dataclass(frozen=True)
class InvariantRequirement:
    number: int
    section: str
    statement: str
    proof_target: str


M07_INVARIANTS = (
    InvariantRequirement(1, 'S01', 'Hardware/runtime observations are evidence, not project, identity, quality, scheduling or execution authority.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(2, 'S01', 'M07 hardware subjects never become M02/M05/M06 semantic identities automatically.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(3, 'S01', 'S01 discovery cannot claim benchmark performance or safe workload limits.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(4, 'S01', 'S01 discovery cannot allocate VRAM/RAM leases or choose offload policy.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(5, 'S01', 'Every admitted observation records an exact observation time.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(6, 'S01', 'Every admitted observation binds an exact probe/source adapter version.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(7, 'S01', '`UNKNOWN` cannot be coerced to `OBSERVED` or `NOT_PRESENT_PROVEN`.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(8, 'S01', '`PERMISSION_DENIED`, `UNSUPPORTED_PROBE`, `UNAVAILABLE` and `PARTIAL` cannot prove absence.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(9, 'S01', 'Materially conflicting admitted sources remain explicit.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(10, 'S01', 'Hot-plug/removal creates new history instead of rewriting prior discovery snapshots.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(11, 'S01', 'Multiple GPUs/adapters remain separately addressable; device index zero is never canonical “the GPU.”', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(12, 'S01', 'Dedicated VRAM and shared/system memory are distinct facts.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(13, 'S01', 'Installed memory and currently available memory are distinct facts.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(14, 'S01', 'Static capacity and dynamic pressure are distinct facts.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(15, 'S01', 'CPU physical/logical/NUMA topology cannot be silently inferred when unavailable.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(16, 'S01', 'Host architecture and current process architecture are distinct when emulation/translation exists.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(17, 'S01', 'Container/VM/WSL visibility cannot be treated automatically as complete physical-host truth.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(18, 'S01', 'Storage discovery does not transfer M55 physical-storage authority to M07.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(19, 'S01', 'Paths, labels, device indices and mutable locators are not canonical semantic identity.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(20, 'S01', 'Raw serial/host identifiers are not collected without a justified privacy-classified need.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(21, 'S01', 'Unsupported platform APIs fail explicitly rather than fabricating portable facts.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(22, 'S01', 'Probe timeout, truncation or resource-limit exhaustion cannot yield a complete snapshot.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(23, 'S01', 'Normal discovery probes are read-only and may not alter hardware/driver/runtime state.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(24, 'S01', 'Arbitrary shell strings or payload-directed commands are forbidden in discovery.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(25, 'S01', '8 GB VRAM-class hardware remains a first-class valid discovery subject.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(26, 'S01', 'Hardware scarcity cannot lower M01 quality targets or M03 semantic obligations.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(27, 'S01', 'Discovery snapshots are immutable and superseded only by new snapshots.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(28, 'S01', 'Evidence digests prove observation payloads and never become hardware identity.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(29, 'S01', 'M06 may treat hardware/runtime facts as reconstruction material only through explicit declared materiality.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(30, 'S01', 'HIVE, agents and UI clients may request/observe discovery but cannot fabricate admitted hardware facts.', 'tests/test_m07_discovery.py::TestDiscovery'),
    InvariantRequirement(31, 'S02', 'Backend/package presence alone cannot prove operational device capability.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(32, 'S02', 'Capability evidence is exact-subject bound.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(33, 'S02', 'Capability evidence is exact-runtime-scope bound.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(34, 'S02', 'Evidence strength cannot increase without new evidence.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(35, 'S02', 'Smoke verification cannot be treated as a benchmark.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(36, 'S02', 'M07 cannot convert capability evidence into scheduler preference.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(37, 'S02', 'M07 cannot convert capability evidence into workload-safe memory limits.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(38, 'S02', 'Driver version, runtime version, toolkit version and library version remain distinct facts.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(39, 'S02', 'A driver-reported compatibility level does not prove a matching toolkit/library installation.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(40, 'S02', 'Framework backend availability does not prove device binding.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(41, 'S02', 'Vendor identity does not prove backend availability.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(42, 'S02', 'Software/emulated adapters remain distinguishable from physical hardware adapters.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(43, 'S02', 'CUDA/ROCm/DirectML/Metal are peer backend families in the M07 schema, not a priority order.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(44, 'S02', 'CPU-only/portable backends remain valid capability subjects.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(45, 'S02', 'Precision support cannot be represented safely as one undifferentiated boolean.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(46, 'S02', 'Reported acceleration is not empirical performance proof.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(47, 'S02', 'Precision capability cannot authorize a quality downgrade.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(48, 'S02', 'Vendor marketing names cannot establish normalized semantic equivalence.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(49, 'S02', 'Conflicting normalized capability evidence remains explicit.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(50, 'S02', 'A weaker/staler source cannot silently overwrite stronger/fresher exact-subject evidence.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(51, 'S02', 'One device may expose multiple backend paths without identity collapse.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(52, 'S02', 'Host-level backend presence cannot be broadcast to every device.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(53, 'S02', 'Cross-device peer/interconnect support requires explicit exact-pair evidence.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(54, 'S02', 'Capability snapshots are immutable.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(55, 'S02', 'Driver/runtime/topology changes can invalidate capability freshness.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(56, 'S02', 'Untrusted library paths cannot become privileged discovery execution.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(57, 'S02', 'Environment variables are evidence, not commands.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(58, 'S02', 'Optional conformance probes must be bounded and non-stress.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(59, 'S02', '8 GB VRAM-class hardware cannot be rejected solely because a later workload may exceed capacity.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(60, 'S02', 'Capability mapping cannot claim M08 benchmark envelopes, M09 resource policy, M10 execution plans or M14 empirical model fitness.', 'tests/test_m07_capabilities.py::TestCapabilitySurfaces'),
    InvariantRequirement(61, 'S03', 'Driver state cannot collapse into one undifferentiated “OK” boolean.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(62, 'S03', 'Higher driver/runtime version cannot be assumed preferable or compatible.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(63, 'S03', 'Host/container/guest/framework runtime skew remains explicit.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(64, 'S03', 'Installed artifacts cannot prove the active runtime path.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(65, 'S03', 'Driver compatibility evidence must bind an exact subject/runtime scope.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(66, 'S03', 'Precision marketing labels cannot replace exact semantic dimensions.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(67, 'S03', 'FP8/sub-byte families remain encoding-specific when semantics differ.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(68, 'S03', 'Reported precision acceleration cannot prove workload quality.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(69, 'S03', 'Reduced precision support cannot authorize silent quality downgrade.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(70, 'S03', 'Codec support is exact device/engine/API/path evidence, not host-wide truth.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(71, 'S03', 'Encode and decode capabilities remain distinct.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(72, 'S03', 'Codec profile/level/bit-depth/chroma features remain explicit where material.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(73, 'S03', 'A successful bounded codec smoke check cannot prove real-time throughput.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(74, 'S03', 'Static reported codec limits cannot prove sustainable production envelopes.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(75, 'S03', 'One successful media session cannot prove concurrency capacity.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(76, 'S03', 'Marketing/session folklore cannot become admitted concurrency evidence.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(77, 'S03', 'Device topology edges require evidence.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(78, 'S03', 'PCIe maximum capability and negotiated state remain distinct.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(79, 'S03', 'Negotiated PCIe state cannot be represented as measured bandwidth.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(80, 'S03', 'Peer capability is exact-pair and direction-aware evidence.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(81, 'S03', 'Multiple GPUs do not imply peer access.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(82, 'S03', 'M07 topology cannot choose sharding, placement or scheduler policy.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(83, 'S03', 'Unified physical memory, shared aperture and managed/unified runtime memory remain distinct.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(84, 'S03', 'Static memory topology cannot authorize oversubscription/offload.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(85, 'S03', 'Virtual/partitioned devices remain distinct from physical parents.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(86, 'S03', 'Hidden physical parent state remains unknown rather than inferred.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(87, 'S03', 'Guest-visible hardware remains valid even when host topology is unavailable.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(88, 'S03', 'Media/compute interop evidence binds exact APIs and subject/runtime scope.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(89, 'S03', 'Interop capability cannot prove a future provider/DCC integration exists.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(90, 'S03', 'Driver/precision/media/topology conflicts remain explicit until governed resolution.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(91, 'S03', 'Driver/topology/runtime changes invalidate affected current-state evidence.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(92, 'S03', 'Discovery cannot mutate driver, firmware, clocks, power or device modes.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(93, 'S03', 'Codec discovery cannot require arbitrary untrusted media input.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(94, 'S03', 'Conformance media fixtures must be fixed, synthetic and bounded.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(95, 'S03', 'Raw vendor-tool output cannot bypass normalized evidence contracts.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(96, 'S03', 'M07 cannot convert topology into M08 performance claims.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(97, 'S03', 'M07 cannot convert topology into M09 resource policy.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(98, 'S03', 'M07 cannot convert topology into M10/M12 execution placement.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(99, 'S03', '8 GB hardware retains full precision/media/topology representation without categorical downgrade.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(100, 'S03', 'HIVE/UI/agents may consume S03 evidence but cannot manufacture or override admitted hardware truth.', 'tests/test_m07_hardware_surfaces.py::TestPrecisionMediaTopology'),
    InvariantRequirement(101, 'S04', 'Dynamic telemetry remains distinct from static hardware/capability facts.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(102, 'S04', 'Every admitted sample binds exact subject, metric, unit and time semantics.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(103, 'S04', 'Counters cannot become rates without a valid interval.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(104, 'S04', 'Reported limits cannot masquerade as current measurements.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(105, 'S04', 'Configured limits cannot masquerade as consumption.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(106, 'S04', 'Distinct thermal sensors cannot be silently averaged into “system temperature.”', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(107, 'S04', 'Missing sensors cannot become zero.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(108, 'S04', 'Lower clocks alone cannot prove throttling cause.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(109, 'S04', 'Throttling reasons remain evidence-bound.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(110, 'S04', 'Power measurement domains and units remain explicit.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(111, 'S04', 'Energy-derived power requires valid counter and interval semantics.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(112, 'S04', 'M07 cannot mutate power limits.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(113, 'S04', 'Current/requested/base/boost/max clocks remain distinct.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(114, 'S04', 'Clock telemetry cannot become benchmark evidence.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(115, 'S04', 'Utilization metrics retain source sampling semantics.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(116, 'S04', 'Same-unit vendor metrics cannot be assumed semantically equivalent.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(117, 'S04', 'Dynamic free VRAM cannot become a safe allocation budget.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(118, 'S04', 'Device-memory telemetry cannot overwrite static capacity/topology truth.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(119, 'S04', 'Host free and available memory remain distinct where supported.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(120, 'S04', 'Container/guest memory limits remain authoritative for their runtime scope.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(121, 'S04', 'Memory pressure cannot be inferred from an undocumented arbitrary threshold.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(122, 'S04', 'Derived pressure states require a versioned derivation rule.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(123, 'S04', 'Pressure evidence cannot directly become execution policy.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(124, 'S04', 'Process telemetry follows least privilege and identity minimization.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(125, 'S04', 'Hardware telemetry cannot retain unrelated command lines/environment/user paths.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(126, 'S04', 'Sampling frequency and window are bounded.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(127, 'S04', 'Busy-loop telemetry polling is prohibited.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(128, 'S04', 'Consumers cannot silently escalate telemetry privilege/frequency.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(129, 'S04', 'M07 telemetry windows remain bounded; long-term observability belongs to M56.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(130, 'S04', 'Derived telemetry binds source samples and derivation version.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(131, 'S04', 'Derived telemetry cannot erase raw evidence.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(132, 'S04', 'Invalid NaN/Infinity/impossible values cannot enter admitted truth.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(133, 'S04', 'Unit-required metrics cannot be admitted unitless.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(134, 'S04', 'Counter reset/wrap/regression semantics must be explicit.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(135, 'S04', 'Stale samples cannot represent current state.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(136, 'S04', 'Zero is accepted only when source semantics make zero meaningful.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(137, 'S04', 'Sensor reconciliation requires semantic identity evidence.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(138, 'S04', 'Conflicting sensors/sources remain explicit.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(139, 'S04', 'Telemetry freshness may vary by metric class.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(140, 'S04', 'Material subject/runtime/source changes invalidate current telemetry windows.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(141, 'S04', 'Historical telemetry evidence remains immutable after invalidation.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(142, 'S04', 'S04 probes cannot tune fans, voltage, clocks, power or performance modes.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(143, 'S04', 'S04 probes cannot kill/suspend processes or evict unrelated allocations.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(144, 'S04', 'S04 cannot allocate large buffers or stress hardware to infer pressure.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(145, 'S04', 'Active performance characterization remains M08 authority.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(146, 'S04', 'Low transient free VRAM cannot classify an 8 GB device as categorically deficient.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(147, 'S04', 'Quality cannot be silently lowered from pressure telemetry.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(148, 'S04', 'Multi-device telemetry remains exact-device scoped.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(149, 'S04', 'Shared sensor/rail values remain explicitly shared rather than duplicated as device-local truth.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(150, 'S04', 'Cross-vendor normalization cannot erase materially different metric semantics.', 'tests/test_m07_telemetry.py::TestTelemetry'),
    InvariantRequirement(151, 'S05', 'Canonical GenomeId is evidence/content anchored, not display-name anchored.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(152, 'S05', 'Schema version and producer version remain separate.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(153, 'S05', 'Canonical genome sections preserve provenance and uncertainty.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(154, 'S05', 'Every admitted fact uses a normalized evidence envelope.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(155, 'S05', 'Raw payloads cannot replace normalized fact envelopes.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(156, 'S05', 'Required unknown states cannot disappear through field omission.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(157, 'S05', 'NOT_PRESENT_PROVEN remains distinct from unknown/unavailable.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(158, 'S05', 'Confidence is multidimensional, not one opaque percentage.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(159, 'S05', 'Composite confidence cannot strengthen semantic claims.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(160, 'S05', 'Repetition of weak evidence cannot automatically promote confidence.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(161, 'S05', 'Newer timestamp alone cannot promote evidence strength.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(162, 'S05', 'Hidden unknowns/conflicts cannot increase confidence.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(163, 'S05', 'Conflicts cannot be averaged away.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(164, 'S05', 'Preferred projections cannot erase conflicting source evidence.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(165, 'S05', 'Schema compatibility rules are machine-readable and versioned.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(166, 'S05', 'PATCH cannot alter admitted semantics.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(167, 'S05', 'MINOR remains backward-compatible under declared reader rules.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(168, 'S05', 'Incompatible semantics require MAJOR versioning.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(169, 'S05', 'Unknown required semantics fail closed.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(170, 'S05', 'Readers cannot silently reinterpret newer semantic states.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(171, 'S05', 'Writers cannot mislabel incompatible semantics as an older schema.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(172, 'S05', 'Canonical storage cannot depend on lossy downgrade.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(173, 'S05', 'Extensions are namespaced.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(174, 'S05', 'Extensions cannot override or weaken canonical semantics.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(175, 'S05', 'Extensions cannot inject executable behavior.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(176, 'S05', 'Extension promotion requires governance/compatibility review.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(177, 'S05', 'Admitted genome snapshots are immutable.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(178, 'S05', 'New snapshots supersede projections, not historical evidence.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(179, 'S05', 'Incomplete snapshots remain explicitly incomplete.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(180, 'S05', 'Deltas bind exact base and target genomes.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(181, 'S05', 'Deltas are not authoritative outside bound base/target context.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(182, 'S05', 'Material-change classes do not prescribe downstream reactions.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(183, 'S05', 'Fingerprints bind canonicalization and schema versions.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(184, 'S05', 'Static fingerprints exclude unstable telemetry unless explicitly contracted.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(185, 'S05', 'M06 reproducibility receives only explicitly declared M07 projections.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(186, 'S05', 'M07 cannot decide M06 hardware-equivalence policy.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(187, 'S05', 'M06 cannot manufacture M07 hardware facts.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(188, 'S05', 'Canonical hashing is independent of presentation formatting.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(189, 'S05', 'Absent and explicit-unknown handling is deterministic.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(190, 'S05', 'Redacted views identify source genome and redaction policy.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(191, 'S05', 'Redacted views cannot claim canonical content identity.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(192, 'S05', 'Cryptographic validity cannot prove semantic truth of probe claims.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(193, 'S05', 'Genome federation requires explicit subject reconciliation.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(194, 'S05', 'Fleet collections cannot masquerade as one hardware subject.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(195, 'S05', 'Physical retention/deletion/tiering remains M55 authority.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(196, 'S05', 'Consumers declare material fact/state requirements.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(197, 'S05', 'Consumers cannot strengthen M07 evidence.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(198, 'S05', 'Consumers cannot overwrite canonical genome facts.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(199, 'S05', 'Confidence alone cannot authorize execution.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(200, 'S05', 'Schema migrations bind source/target/version and loss classification.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(201, 'S05', 'Lossy migration cannot replace canonical source genome.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(202, 'S05', 'Deterministic fixtures cover heterogeneous and constrained hardware classes.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(203, 'S05', '8 GB discrete GPUs remain first-class canonical genome subjects.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(204, 'S05', 'CPU-only systems remain first-class canonical genome subjects.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(205, 'S05', 'Missing permissions remain explicit evidence states.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(206, 'S05', 'Stale evidence cannot become current during serialization/migration.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(207, 'S05', 'Conflict state survives serialization, redaction and compatible migration.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(208, 'S05', 'Privacy redaction cannot silently alter capability semantics.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(209, 'S05', 'Hardware Genome cannot become a benchmark ranking.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(210, 'S05', 'Hardware Genome cannot become scheduler/placement policy.', 'tests/test_m07_genome.py::TestGenome'),
    InvariantRequirement(211, 'FC', 'Consumer-specific projections are named and versioned.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(212, 'FC', 'A consumer projection cannot strengthen source genome evidence.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(213, 'FC', 'Projection omission cannot imply an uncaptured fact.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(214, 'FC', 'Capability/metric keys come from a versioned semantic registry or governed namespace.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(215, 'FC', 'Registry entries declare semantic type/unit/evidence requirements where applicable.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(216, 'FC', 'Plugin/provider extensions cannot shadow canonical registry keys.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(217, 'FC', 'Probe descriptors declare explicit permission/capability classes.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(218, 'FC', 'Probe registration cannot grant execution privilege.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(219, 'FC', 'Federated capability advertisements use privacy-safe redacted profiles.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(220, 'FC', 'Redaction cannot remove evidence state/freshness needed for advertised claims.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(221, 'FC', 'Change notifications bind exact prior/current genome or delta identity.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(222, 'FC', 'Change events describe evidence change, not downstream policy action.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(223, 'FC', 'Benchmark/model/workflow evidence can bind exact genome projection/fingerprint.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(224, 'FC', 'Benchmark bindings cannot convert M07 discovery into benchmark truth.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(225, 'FC', 'Hardware-evidence confidence remains distinct from output-quality confidence.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(226, 'FC', 'Destination-device capability profiles remain outside M07 authority.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(227, 'FC', 'Historical genome restoration cannot create a current-state claim.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(228, 'FC', 'Recovery requires fresh discovery for current hardware truth.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(229, 'FC', 'HIVE retrieval cannot override fresher admitted M07 evidence.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(230, 'FC', 'Agents/plugins cannot manufacture or strengthen M07 evidence.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(231, 'FC', 'DCC/provider extensions remain namespaced and non-authoritative over canonical keys.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(232, 'FC', 'M56 may aggregate telemetry but cannot invent missing M07 samples.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(233, 'FC', 'M55 retention/deletion actions cannot rewrite genome/evidence semantic history.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(234, 'FC', 'M12 federation cannot assume globally stable raw device identifiers.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
    InvariantRequirement(235, 'FC', 'M60 acceptance can require hardware-class evidence without redefining M07 fact semantics.', 'tests/test_m07_authority.py::TestProjectionAndRecovery'),
)

M07_INVARIANT_MAP = MappingProxyType({item.number: item for item in M07_INVARIANTS})


def validate_invariant_catalog() -> None:
    expected = tuple(range(1, 236))
    numbers = tuple(item.number for item in M07_INVARIANTS)
    if numbers != expected or len(M07_INVARIANT_MAP) != 235:
        raise HardwareGenomeIntegrityError("M07 hard invariants must be numbered exactly 1 through 235")
    counts = {section: sum(item.section == section for item in M07_INVARIANTS) for section in ("S01", "S02", "S03", "S04", "S05", "FC")}
    if counts != {"S01": 30, "S02": 30, "S03": 40, "S04": 50, "S05": 60, "FC": 25}:
        raise HardwareGenomeIntegrityError("M07 invariant section counts differ from the frozen contract")
    if any(not item.statement or not item.proof_target.startswith("tests/test_m07_") for item in M07_INVARIANTS):
        raise HardwareGenomeIntegrityError("every M07 invariant requires literal text and a focused proof target")
