"""Provider-neutral, runtime-neutral multimodal semantic IR kernel (M04)."""

from .character import AttachmentPortIR, CharacterIdentityIR, JointIR, JointWeight, MorphChannelIR, SkeletonIR, SkinBindingIR
from .context import (
    CapabilitySlice,
    IRCanonicalSliceRecord,
    IRInterfaceFingerprint,
    IRSemanticDelta,
    IRStructuralFingerprint,
    IRSubgraphFingerprint,
    MinimumSufficientIRSlice,
    MinimumSufficientTemporalSlice,
    SemanticRecordChange,
    build_capability_slice,
    build_ir_slice,
    build_temporal_slice,
    interface_fingerprint,
    semantic_delta,
    structural_fingerprint,
    subgraph_fingerprint,
)
from .enums import (
    CompositionPrecedence,
    CyclePolicy,
    EquivalenceKind,
    MusicEventKind,
    NodeKind,
    Physicality,
    ProjectionKind,
    QuantityDimension,
    ReadinessState,
    RepresentationState,
    RequirementLevel,
    SchemaUnknownPolicy,
    SemanticLossClass,
    SupportState,
    SyncKind,
    TemporalLayer,
    ValidationSeverity,
)
from .errors import (
    IRAdmissionError,
    IRIntegrityError,
    IRKernelError,
    IRLimitError,
    IRSchemaError,
)
from .graph import (
    AssetIR,
    CollectionIR,
    CompositionArc,
    CompositionResult,
    ContainmentEdge,
    CharacterIR,
    EntityIR,
    GeometryIR,
    IRDocumentEnvelope,
    IRFragment,
    IRNode,
    IRRevision,
    MultimodalIRDocument,
    PrototypeIR,
    RelationshipPolicy,
    SceneIR,
    SemanticRelationship,
    InstanceIR,
    compose_fragments,
    decode_ir_node,
    find_transform_path,
    validate_graph,
)
from .identity import (
    AssetDNARef,
    ExternalIdentityRef,
    IRNodeRef,
    IRRevisionRef,
    IdentityAnchorRef,
    PersonaDNARef,
    ResourceLocatorRef,
    ResourceRef,
    SemanticRef,
)
from .invariants import FROZEN_INVARIANT_PROOFS, FrozenInvariantProof, validate_invariant_proof_index
from .limits import DEFAULT_LIMITS, IRLimits
from .lowering import (
    AdaptationProposal,
    CapabilityDeclaration,
    CapabilitySupport,
    IRTranslationReceipt,
    LegalityFinding,
    LoweringBundlePlan,
    M03ToM04Mapping,
    RepresentationCapabilityManifest,
    RepresentationGap,
    SemanticCapabilityDebt,
    SemanticLegalityReport,
    SemanticLoweringPlan,
    SemanticLoweringReceipt,
    SemanticLoweringRule,
    TargetRepresentationProfile,
    analyze_legality,
    lower_m03_bundle,
    plan_semantic_lowering,
)
from .materials import (
    ColorConversionReceipt,
    ColorPipelineRef,
    ColorValueIR,
    MaterialBindingIR,
    MaterialConnectionIR,
    MaterialGraphIR,
    MaterialIR,
    MaterialNodeIR,
    MaterialPortIR,
    MaterialTerminalIR,
)
from .media import (
    AudioClipBindingIR,
    AudioIR,
    AudioSpatialIR,
    MusicEventIR,
    MusicIR,
    MusicMeterIR,
    MusicSectionIR,
    MusicTempoIR,
    NarrativeCueIR,
    NarrativeProjectionIR,
    PersonaRef,
    SequenceRepresentationIR,
    ShotRepresentationIR,
    SpeakerRef,
    SyncEvaluation,
    SyncRelationIR,
    TimelineIR,
    TimelineItemIR,
    TimelineTrackIR,
    VoiceIdentityRef,
)
from .migration import IRMigrationPlan, IRMigrationReceipt, SchemaMigrationAction, migrate_revision
from .provenance import SemanticFactTrace, TraceOrigin, Traceability
from .readiness import IRReleaseReadinessReport, compute_readiness
from .resources import IRInterfaceCapsule, InterfacePort, PayloadDescriptor, ResourceRequirement, TextureResourceIR
from .roundtrip import (
    ComparisonTolerance,
    IREquivalenceProfile,
    RoundTripContract,
    RoundTripDifference,
    RoundTripReceipt,
    SemanticWitness,
    SemanticWitnessSet,
    build_round_trip_contract,
    build_witness_set,
    verify_round_trip,
)
from .schema import (
    CORE_SCHEMA_FAMILIES,
    DialectRef,
    ExtensionValue,
    FacetRef,
    SchemaCompatibilityDeclaration,
    SchemaFamilyRef,
    SchemaManifest,
)
from .serialization import canonical_bytes, canonical_digest, deserialize_envelope, serialize_envelope
from .spatial import (
    CameraIR,
    CameraOpticsIR,
    CoordinateFrameIR,
    LightInfluenceIR,
    LightIR,
    LightShapingIR,
    QuantityIR,
    ResolvedTransform,
    ShadowIntentIR,
    SpatialConversionReceipt,
    SpatialReferenceIR,
    SpatialRegionIR,
    TransformChainIR,
    TransformOperation,
    convert_quantity,
    resolve_transform,
)
from .temporal import (
    AnimationCurveIR,
    CurveKeyIR,
    DurationIR,
    MotionChannelIR,
    MotionClipIR,
    MotionIR,
    MotionLayerIR,
    MotionTargetRef,
    TemporalConversionReceipt,
    TemporalMarkerIR,
    TemporalReferenceIR,
    TemporalRelationIR,
    TemporalSamplingIR,
    TimePointIR,
    TimeRangeIR,
    convert_time_point,
    sample_curve,
)
from .validation import IRValidationFinding, IRValidationProfile, IRValidationReport, validate_envelope, validate_revision
from .versions import (
    CONTRACT_VERSION,
    CORE_SCHEMA_VERSION,
    LOWERING_VERSION,
    TRANSPORT_VERSION,
    VALIDATOR_VERSION,
    canonical_json,
    content_digest,
)

__all__ = [
    "CONTRACT_VERSION", "CORE_SCHEMA_VERSION", "TRANSPORT_VERSION", "VALIDATOR_VERSION", "LOWERING_VERSION",
    "IRKernelError", "IRSchemaError", "IRIntegrityError", "IRAdmissionError", "IRLimitError", "IRLimits", "DEFAULT_LIMITS",
    "IRNodeRef", "IRRevisionRef", "ExternalIdentityRef", "IdentityAnchorRef", "AssetDNARef", "PersonaDNARef", "ResourceLocatorRef", "ResourceRef", "SemanticRef",
    "TraceOrigin", "Traceability", "SemanticFactTrace", "NodeKind", "RequirementLevel", "SupportState", "RepresentationState", "SemanticLossClass", "CyclePolicy", "CompositionPrecedence", "ProjectionKind", "QuantityDimension", "Physicality", "TemporalLayer", "MusicEventKind", "SyncKind", "SchemaUnknownPolicy", "EquivalenceKind", "ReadinessState", "ValidationSeverity",
    "SchemaFamilyRef", "FacetRef", "DialectRef", "SchemaManifest", "ExtensionValue", "SchemaCompatibilityDeclaration", "CORE_SCHEMA_FAMILIES",
    "ResourceRequirement", "InterfacePort", "IRInterfaceCapsule", "PayloadDescriptor", "TextureResourceIR",
    "IRNode", "SceneIR", "EntityIR", "AssetIR", "CharacterIR", "GeometryIR", "CollectionIR", "ContainmentEdge", "SemanticRelationship", "RelationshipPolicy", "IRFragment", "CompositionArc", "CompositionResult", "compose_fragments", "PrototypeIR", "InstanceIR", "IRRevision", "MultimodalIRDocument", "IRDocumentEnvelope", "validate_graph", "find_transform_path", "decode_ir_node",
    "JointIR", "SkeletonIR", "JointWeight", "SkinBindingIR", "MorphChannelIR", "AttachmentPortIR", "CharacterIdentityIR",
    "QuantityIR", "SpatialReferenceIR", "CoordinateFrameIR", "TransformOperation", "TransformChainIR", "ResolvedTransform", "SpatialConversionReceipt", "convert_quantity", "resolve_transform", "CameraOpticsIR", "CameraIR", "LightShapingIR", "ShadowIntentIR", "LightInfluenceIR", "LightIR", "SpatialRegionIR",
    "MaterialPortIR", "MaterialNodeIR", "MaterialConnectionIR", "MaterialTerminalIR", "MaterialGraphIR", "MaterialIR", "MaterialBindingIR", "ColorValueIR", "ColorPipelineRef", "ColorConversionReceipt",
    "TemporalReferenceIR", "TimePointIR", "TimeRangeIR", "DurationIR", "MotionTargetRef", "CurveKeyIR", "AnimationCurveIR", "MotionChannelIR", "MotionIR", "MotionClipIR", "MotionLayerIR", "TemporalSamplingIR", "TemporalMarkerIR", "TemporalRelationIR", "TemporalConversionReceipt", "convert_time_point", "sample_curve",
    "VoiceIdentityRef", "PersonaRef", "SpeakerRef", "AudioSpatialIR", "AudioIR", "AudioClipBindingIR", "MusicTempoIR", "MusicMeterIR", "MusicEventIR", "MusicSectionIR", "MusicIR", "NarrativeCueIR", "NarrativeProjectionIR", "TimelineItemIR", "TimelineTrackIR", "ShotRepresentationIR", "SequenceRepresentationIR", "TimelineIR", "SyncRelationIR", "SyncEvaluation",
    "CapabilityDeclaration", "CapabilitySupport", "RepresentationCapabilityManifest", "TargetRepresentationProfile", "LegalityFinding", "SemanticLegalityReport", "SemanticLoweringRule", "SemanticLoweringReceipt", "SemanticLoweringPlan", "AdaptationProposal", "RepresentationGap", "IRTranslationReceipt", "SemanticCapabilityDebt", "LoweringBundlePlan", "M03ToM04Mapping", "lower_m03_bundle", "analyze_legality", "plan_semantic_lowering",
    "IRValidationProfile", "IRValidationFinding", "IRValidationReport", "validate_revision", "validate_envelope", "SchemaMigrationAction", "IRMigrationPlan", "IRMigrationReceipt", "migrate_revision",
    "ComparisonTolerance", "IREquivalenceProfile", "SemanticWitness", "SemanticWitnessSet", "RoundTripContract", "RoundTripDifference", "RoundTripReceipt", "build_witness_set", "build_round_trip_contract", "verify_round_trip",
    "IRStructuralFingerprint", "IRSubgraphFingerprint", "IRInterfaceFingerprint", "IRSemanticDelta", "SemanticRecordChange", "IRCanonicalSliceRecord", "MinimumSufficientIRSlice", "MinimumSufficientTemporalSlice", "CapabilitySlice", "structural_fingerprint", "subgraph_fingerprint", "interface_fingerprint", "semantic_delta", "build_ir_slice", "build_temporal_slice", "build_capability_slice",
    "IRReleaseReadinessReport", "compute_readiness", "canonical_json", "content_digest", "canonical_bytes", "canonical_digest", "serialize_envelope", "deserialize_envelope", "FrozenInvariantProof", "FROZEN_INVARIANT_PROOFS", "validate_invariant_proof_index",
]
